// AUTO-GENERATED BY tools/revx-gen.mjs – DO NOT EDIT
export type RevelexPermission = { id: string; description?: string };
export type RevelexWindowDef = { title?: string; width?:number;height?:number;minWidth?:number;minHeight?:number;resizable?:boolean;state?:'normal'|'minimized'|'maximized'|'fullscreen' };
export type RevelexApp = {
  id: string; name: string; icon?: string; version: string; main: string;
  category?: string; autostart?: boolean; permissions?: string[];
  windows?: { main?: RevelexWindowDef }
};

export const RevelexDefaults = {
  "window": {
    "width": 800,
    "height": 600,
    "minWidth": 360,
    "minHeight": 240,
    "resizable": true,
    "state": "normal"
  }
} as const;
export const RevelexPermissions: Record<string, RevelexPermission> = {
  "filesystem.read": {
    "id": "filesystem.read",
    "description": "Read files and list directories"
  },
  "filesystem.write": {
    "id": "filesystem.write",
    "description": "Write files and create/remove directories"
  },
  "network.access": {
    "id": "network.access",
    "description": "Fetch remote resources"
  },
  "system.execute": {
    "id": "system.execute",
    "description": "Execute shell or system calls (sandboxed)"
  },
  "system.config": {
    "id": "system.config",
    "description": "Change system settings"
  }
};
export const RevelexApps: RevelexApp[] = [
  {
    "id": "system.desktop",
    "name": "Desktop",
    "icon": "desktop",
    "version": "1.0.0",
    "main": "Desktop",
    "category": "system",
    "autostart": true,
    "windows": {
      "main": {
        "title": "Sanctum Desktop",
        "width": 1280,
        "height": 720,
        "resizable": false
      }
    }
  },
  {
    "id": "system.dock",
    "name": "Dock",
    "icon": "dock",
    "version": "1.0.0",
    "main": "Dock",
    "category": "system",
    "autostart": true,
    "windows": {
      "main": {
        "title": "Dock",
        "width": 800,
        "height": 120,
        "resizable": false
      }
    }
  },
  {
    "id": "system.files",
    "name": "Files",
    "icon": "folder",
    "version": "1.0.0",
    "main": "../apps/Files",
    "category": "utilities",
    "permissions": [
      "filesystem.read",
      "filesystem.write"
    ],
    "windows": {
      "main": {
        "title": "Dateien",
        "width": 900,
        "height": 640
      }
    }
  },
  {
    "id": "system.terminal",
    "name": "Terminal",
    "icon": "terminal",
    "version": "1.0.0",
    "main": "../apps/Terminal",
    "category": "development",
    "permissions": [
      "system.execute"
    ],
    "windows": {
      "main": {
        "title": "Konsole",
        "width": 900,
        "height": 520
      }
    }
  },
  {
    "id": "system.settings",
    "name": "Settings",
    "icon": "settings",
    "version": "1.0.0",
    "main": "../apps/Settings",
    "category": "system",
    "permissions": [
      "system.config"
    ],
    "windows": {
      "main": {
        "title": "Einstellungen",
        "width": 960,
        "height": 640
      }
    }
  },
  {
    "id": "system.browser",
    "name": "Browser",
    "icon": "globe",
    "version": "1.0.0",
    "main": "../apps/Browser",
    "category": "communication",
    "permissions": [
      "network.access"
    ],
    "windows": {
      "main": {
        "title": "Navigator",
        "width": 1024,
        "height": 768
      }
    }
  }
];

// helpers
export function getAutostartApps(): RevelexApp[] { return RevelexApps.filter(a => a.autostart); }
